$script = <<-SCRIPT
dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
dnf -y install 'dnf-command(copr)'
dnf -y copr enable rhcontainerbot/container-selinux
dnf -y install wget
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-8.2"
  config.vm.synced_folder "./shared", "/vagrant"
  config.vm.provision "shell", inline: $script

  for i in 9180..9280
    config.vm.network :forwarded_port, guest: i, host: i
  end

  config.vm.provider "parallels" do |prl|
    prl.name = "vagrant_centos-8.2"
    prl.memory = 2048
    prl.cpus = 2
  end
end
