$script = <<-SCRIPT
  apt -y update && apt -y upgrade
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.synced_folder "./shared", "/vagrant"
  config.vm.provision "shell", inline: $script

  config.vm.provider "parallels" do |prl|
    prl.name = "vagrant_ubuntu-20.04"
    prl.memory = 2048
    prl.cpus = 2
  end
end
