$script = <<-SCRIPT
sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
  build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
  xz-utils debianutils iputils-ping

git clone git://git.openembedded.org/openembedded-core /home/vagrant/oe-core
git clone git://git.openembedded.org/bitbake /home/vagrant/oe-core/bitbake
git -C /home/vagrant/oe-core checkout zeus
git -C /home/vagrant/oe-core/bitbake checkout 1.46

echo "source /home/vagrant/oe-core/oe-init-build-env /build" >> /home/vagrant/.bashrc
SCRIPT
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.synced_folder "./build", "/build"
  config.vm.provision "shell", inline: $script
  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", "8192"]
    vb.customize ["modifyvm", :id, "--cpus", "8"]
  end
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 6
    libvirt.memory = 8192
    libvirt.graphics_type = "none"
  end
end
